-
  name: box-ng setup
  hosts: localhost
  tasks:
    - name: pacman -Syu
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install tools
      pacman:
        name: neovim, ripgrep
        state: latest

    - name: Install development software
      pacman:
        name: code, nodejs, jq, jdk-openjdk, maven, python, python-pip
        state: latest

    - name: Create workspace directory
      file:
        path: ~/devops_directory
        state: directory
