-
  name: box-ng setup
  hosts: localhost
  tasks:
    - name: Run the equivalent of "pacman -Syu"
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install misc
      become: yes
      package:
        name: '{{ item }}'
        state: latest
        use: pacman
      with_items:
        - gimp
        - libreoffice-fresh
        - steam-manjaro

    - name: Install tools
      become: yes
      package:
        name: '{{ item }}'
        state: latest
        use: pacman
      with_items:
        - filezilla
        - firefox
        - galculator
        - gnu-netcat
        - manjaro-printer
        - neovim
        - nmap
        - ranger
        - ripgrep
        - tmux
        - tree
        - virtualbox
        - yay

    - name: Install work software
      become: yes
      package:
        name: '{{ item }}'
        state: latest
        use: pacman
      with_items:
        - kubectl
        - terraform

    - name: Install development software
      become: yes
      package:
        name: '{{ item }}'
        state: latest
        use: pacman
      with_items:
        - base-devel
        - code
        - nodejs
        - npm
        - jq
        - jdk-openjdk
        - maven
        - postgresql
        - python
        - python-pip
        - docker
        - docker-compose
        - yarn

    # - name: Install packages from AUR
    #   command: yay -S --answerclean=no --answerdiff=n --removemake {{ item }}
    #   with_items:

    - name: Enable docker service and start it
      become: yes
      service:
        name: docker
        enabled: yes

    - name: Enable printer service and start it
      become: yes
      service:
        name: org.cups.cupsd
        enabled: yes

    - name: Configure clipman
      xfconf:
        channel: "xfce4-panel"
        property: "/plugins/clipman/settings/save-on-quit"
        value_type: "bool"
        value: "false"

    - name: Configure keyboard layout #1
      xfconf:
        channel: "keyboard-layout"
        property: "/Default/XkbLayout"
        value_type: "string"
        value: "us,gr"

    - name: Configure keyboard layout #2
      xfconf:
        channel: "keyboard-layout"
        property: "/Default/XkbVariant"
        value_type: "string"
        value: ","

    - name: Configure keyboard layout #3
      xfconf:
        channel: "keyboard-layout"
        property: "/Default/XkbOptions/Group"
        value_type: "string"
        value: "grp:alt_shift_toggle"

    # - name: Install vscode extensions
    #   command: code --install-extension {{ item }}
    #   with_items:
    #     - eamodio.gitlens
    #     - esbenp.prettier-vscode
    #     - rbbit.typescript-hero
    #     - vscodevim.vim
    #     - dbaeumer.vscode-eslint

    - name: Add settings to .bashrc
      lineinfile:
        path: ~/.bashrc
        line: '{{ item }}'
      with_items:
        - set -o vi
        - alias vi='nvim'
        - alias vim='nvim'

    - name: Create workspace directory
      file:
        path: ~/workspace
        state: directory

    - name: Create nvim directory
      file:
        path: ~/.config/nvim/
        state: directory

    - name: Copy configuration files
      copy:
        src:  '{{ item }}'
        dest: ~/{{ item }}
      with_items:
        - .config/nvim/init.vim
        - .gitconfig
        - .tmux.conf

    - name: Install vim-plug and install plugins
      shell: |
        curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        nvim --headless +PlugInstall +qall
      args:
        warn: no

    # - name: Add alex user to bumblebee group
    #   become: yes
    #   user:
    #     name: alex
    #     group: bumblebee
    #     append: yes

    # - name: Set terminal font
    #   lineinfile:
    #     path: ~/.config/xfce4/terminal/terminalrc
    #     regex: FontName
    #     line: 'FontName=Noto Sans Mono Medium'

    # - name: Add shortcut for volume up
    #   lineinfile:
    #     path: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
    #     regexp: 'Super&gt;Page_Up'
    #     insertafter: Super(_L|&gt;r)
    #     line: '      <property name="&lt;Super&gt;Page_Up" type="string" value="pulseaudio-ctl up"/>'

    # - name: Add shortcut for volume down
    #   lineinfile:
    #     path: ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
    #     regexp: 'Super&gt;Page_Down'
    #     insertafter: Super(_L|&gt;r)
    #     line: '      <property name="&lt;Super&gt;Page_Down" type="string" value="pulseaudio-ctl down"/>'

    # - name: Set number of workspaces to 1
    #   command: xfconf-query -c xfwm4 -p /general/workspace_count -s 1
