-
  name: box-ng setup
  hosts: localhost
  tasks:
    - name: pacman -Syu
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install tools
      become: yes
      pacman:
        name: {{ item }}
        state: latest
      with_items:
        - neovim
        - ripgrep

    - name: Install development software
      become: yes
      pacman:
        name: {{ item }}
        state: latest
      with_items:
        - code
        - nodejs
        - jq
        - jdk-openjdk
        - maven
        - python
        - python-pip

    # At some point I need to automate this for changing versions
    - name: Change java version to 11
      become: yes
      command: archlinux-java set java-11-openjdk

    - name: Install vscode extensions
      command: code --install-extension {{ item }}
      with_items:
        - eamodio.gitlens
        - esbenp.prettier-vscode
        - rbbit.typescript-hero
        - vscodevim.vim
        - dbaeumer.vscode-eslint

    - name: Create workspace directory
      file:
        path: ~/workspace
        state: directory
