-
  name: box-ng setup
  hosts: localhost
  tasks:
    - name: Update pacman
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install packages
      pacman:
        name: firefox
        state: present
