-
  name: box-ng setup
  hosts: localhost
  tasks:
    - name: pacman -Syu
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install vscode
      pacman:
        name: code
        state: latest

    - name: Create workspace directory
      file:
        path: ~/devops_directory
        state: directory
