-
  name: box-ng setup
  hosts: localhost
  tasks:
    - name: Update pacman
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install packages
      pacman:
        name: 
          - code
          - firefox
          - neovim
          - ranger
          - terraform
        state: present

    - name: Create neovim configuration folder
      file:
        path: /home/alpanagi/.config/nvim/
        state: directory

    - name: Configure neovim
      copy:
        src: .config/nvim/init.vim
        dest: /home/alpanagi/.config/nvim/init.vim
        owner: alpanagi
        group: alpanagi
