-
  name: box-ng setup
  hosts: localhost
  tasks:
    - name: Update pacman
      pacman:
        update_cache: yes
        upgrade: yes
      become: yes

    - name: Install packages
      pacman:
        name: 
          - code
          - firefox
          - neovim
          - ranger
          - terraform
          - tmux
        state: present
      become: yes

    - name: Create neovim configuration folder
      file:
        path: /home/alpanagi/.config/nvim/
        state: directory

    - name: Download vim-plug
      shell: curl -fLo /home/alpanagi/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    - name: Configure neovim
      copy:
        src: .config/nvim/init.vim
        dest: /home/alpanagi/.config/nvim/init.vim

    - name: Install plugins
      shell: nvim +PlugInstall +qall

    - name: Configure tmux
      copy:
        src: .config/.tmux.conf
        dest: /home/alpanagi/.tmux.conf
